### ISSUE TITLE
unable to start server

### ISSUE THREAD

**Issue by zakpatat** [MRVDH/picnic-web#14]
`    at FSReqCallback.oncomplete (node:fs:201:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
`

**Comment by MRVDH** [comment]
This does not seem like something related to this app. Do you have more debug info?

**Comment by johanflikweert** [comment]
See stacktrace below

```
C:\nodejs\picnic-web\client>npm run serve

> picnic-web-client@1.0.0 serve 
> vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
10% building 2/4 modules 2 active C:\nodejs\picnic-web\client\node_modules\webpack\hot\dev-server.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\nodejs\picnic-web\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\nodejs\picnic-web\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\nodejs\picnic-web\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active ..._modules\eslint-loader\index.js??ref--13-0!C:\nodejs\picnic-web\client\src\main.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\nodejs\picnic-web\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\nodejs\picnic-web\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\nodejs\picnic-web\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\nodejs\picnic-web\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\nodejs\picnic-web\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\nodejs\picnic-web\client\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
